### ISSUE TITLE
Repository name case

### ISSUE THREAD

**Issue by hanshuebner** [xquery-mode/Oook-selector#1]
Please rename the repository to "oook-selector" so that the name case matches what the various documentation files say.

**Comment by proofit404** [comment]
Should we rename Oook as well?

**Comment by hanshuebner** [comment]
I would think so, yes.  Lower case is preferable, and things need to be consistent.

**Comment by proofit404** [comment]
OK, I'll do that after my flight to Russia.

**Comment by proofit404** [comment]
Done.
